apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: consumer
        imagePullPolicy: IfNotPresent