apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-user
spec:
  replicas: 0
  selector:
    matchLabels:
      app: dummy-user
  template:
    metadata:
      labels:
        app: dummy-user
    spec:
      containers:
      - name: dummy-user
        image: dummy-user
        imagePullPolicy: IfNotPresent
