apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: host.minikube.internal:5001/fastapi:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: db-volume
              mountPath: /data
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: sqlite-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
